// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"go-dependency-injection/app"
	"go-dependency-injection/config"
	"go-dependency-injection/controller"
	"go-dependency-injection/helper"
	"go-dependency-injection/middleware"
	"go-dependency-injection/repository"
	"go-dependency-injection/router"
	"go-dependency-injection/service"
	"net/http"
)

// Injectors from injector.go:

func InitializeServer() *http.Server {
	productRepository := repository.NewProductRepository()
	db := config.NewDB()
	validate := helper.NewValidator()
	productService := service.NewProductService(productRepository, db, validate)
	productController := controller.NewProductController(productService)
	httprouterRouter := router.NewRouter(productController)
	authMiddleware := middleware.NewAuthMiddleware(httprouterRouter)
	server := app.NewServer(authMiddleware)
	return server
}
