// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package example

// Injectors from injector.go:

func InitializeExampleController(isError bool) (*ExampleController, error) {
	exampleRespository := NewExampleRepository(isError)
	exampleService, err := NewExampleService(exampleRespository, isError)
	if err != nil {
		return nil, err
	}
	exampleController, err := NewExampleController(exampleService)
	if err != nil {
		return nil, err
	}
	return exampleController, nil
}
